CREATE TABLE `product` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(1000) NOT NULL,
`code` VARCHAR(50) NOT NULL,
`price` VARCHAR(200) NOT NULL,
`category` ENUM('CLOTHING', 'ELECTRONICS', 'FOOD', 'HEALTH&BEAUTY') NOT NULL,
`brand` ENUM('RFL', 'ZARA', 'APPLE', 'GUCCI', 'UNILEVER') NOT NULL,
`details` VARCHAR(3000) NOT NULL,
`is_deleted` BIT NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`));